In [2]:
print('hello world')


hello world


In [4]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [6]:
# So, here is ? mark represents the help as a shorthand

len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [9]:
L = [1, 2, 3]
L.insert?

Signature: L.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method

In [11]:
L?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [13]:
def square(a):
    """Return the square a."""
    return a ** 2

In [15]:
square??

Signature: square(a)
Source:   
def square(a):
    """Return the square a."""
    return a ** 2
File:      /var/folders/j4/qzhh77r553z1scwnh3mxkx200000gn/T/ipykernel_5439/4190633865.py
Type:      function

In [17]:
len??

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method

In [19]:
L.<TAB>

SyntaxError: invalid syntax (3745167853.py, line 1)

In [6]:
L.

SyntaxError: invalid syntax (3399076706.py, line 1)

In [21]:
L.<TAB>

SyntaxError: invalid syntax (3745167853.py, line 1)

In [24]:
L.append(4)

In [26]:
print(L)

[1, 2, 3, 4]


In [28]:
L.__delitem__(3)

In [30]:
L?

Type:        list
String form: [1, 2, 3]
Length:      3
Docstring:  
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.

In [ ]:
# You can see that __delitem__ deleted the 3rd item which was 4 

In [32]:
from itertools import co # press tab keyboard when you want to get a result

ImportError: cannot import name 'co' from 'itertools' (unknown location)

In [34]:
import # pressed tab shows the whole third-part scripts and modules

SyntaxError: invalid syntax (4116811366.py, line 1)

In [36]:
import h # pressed tab helps you find the exact order that start with h 

ModuleNotFoundError: No module named 'h'

In [38]:
*Warning?  # beyond tab completion: Wildcard matching 

BytesWarning
DeprecationWarning
EncodingWarning
FutureWarning
ImportWarning
PendingDeprecationWarning
ResourceWarning
RuntimeWarning
SyntaxWarning
UnicodeWarning
UserWarning
Warning

In [40]:
str.*find*?   # suppose we're looking for a string method that contains the word
# find somewhere it its name.

str.find
str.rfind

In [ ]:
# he asdasdasdasdsadadad    


# ctrl + d --> delete next character in line 
# ctrl + k --> cut text from cursor to end of line 
# ctrl + u --> cut text from beginning of line to cursor 
# ctrl + y --> yank ( ..paste) etxt that was previously cut 
# ctrl + t --> Transpose (...switch) previous two characters

asdsasassa

In [19]:
def func1(a,b):
    return a / b

def func2(x):
    a = x
    b = x - 1 
    return func1(a,b)
    

In [21]:
func2(1)


ZeroDivisionError: division by zero

In [23]:
def func2(x):
    a = x

%xmode Plain

In [27]:
func2(1)

In [29]:
%xmode Verbose

Exception reporting mode: Verbose


In [36]:
func2(1)

In [ ]:
%debug

> /opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py(1305)_input_request()
   1303                 # re-raise KeyboardInterrupt, to truncate traceback
   1304                 msg = "Interrupted by user"
-> 1305                 raise KeyboardInterrupt(msg) from None
   1306             except Exception:
   1307                 self.log.warning("Invalid Message:", exc_info=True)



ipdb>  
ipdb>  
ipdb>  up


> /opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py(1262)raw_input()
   1260             msg = "raw_input was called, but this frontend does not support input requests."
   1261             raise StdinNotImplementedError(msg)
-> 1262         return self._input_request(
   1263             str(prompt),
   1264             self._parent_ident["shell"],



ipdb>  down


> /opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py(1305)_input_request()
   1303                 # re-raise KeyboardInterrupt, to truncate traceback
   1304                 msg = "Interrupted by user"
-> 1305                 raise KeyboardInterrupt(msg) from None
   1306             except Exception:
   1307                 self.log.warning("Invalid Message:", exc_info=True)



ipdb>  print(x)


*** NameError: name 'x' is not defined


ipdb>  up


> /opt/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py(1262)raw_input()
   1260             msg = "raw_input was called, but this frontend does not support input requests."
   1261             raise StdinNotImplementedError(msg)
-> 1262         return self._input_request(
   1263             str(prompt),
   1264             self._parent_ident["shell"],



In [10]:
%%time
total = 0
for i in range(1000):
    for j in range(1000):
        total += i * (-1) ** j
        

CPU times: user 111 ms, sys: 3.66 ms, total: 115 ms
Wall time: 119 ms


In [5]:
def sum_of_lists(N):
    total = 0
    for i in range(5):
        L = [j ^ (j >> i) for j in range(N)]
        total += sum(L)
    return total 

In [16]:
%prun sum_of_lists(1000000)

         674 function calls (663 primitive calls) in 0.204 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.088    0.088    0.095    0.095 1773548912.py:1(sum_of_lists)
       14    0.076    0.005    0.082    0.006 socket.py:621(send)
        5    0.013    0.003    0.013    0.003 {built-in method builtins.sum}
      2/1    0.012    0.006    0.006    0.006 {method 'control' of 'select.kqueue' objects}
        2    0.006    0.003    0.095    0.047 zmqstream.py:607(_handle_events)
      4/2    0.004    0.001    0.099    0.049 events.py:86(_run)
        1    0.004    0.004    0.099    0.099 <string>:1(<module>)
        5    0.000    0.000    0.000    0.000 attrsettr.py:65(_get_attr_opt)
        1    0.000    0.000    0.012    0.012 history.py:55(only_when_enabled)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
       15    0.000    0.000    0.000    0.000 enum.py:155

In [18]:
pip install line_profiler

Note: you may need to restart the kernel to use updated packages.


In [1]:
%load_ext line_profiler

In [7]:
%lprun -f sum_of_lists sum_of_lists(5000)

Timer unit: 1e-09 s

Total time: 0.011039 s
File: /var/folders/j4/qzhh77r553z1scwnh3mxkx200000gn/T/ipykernel_1596/1773548912.py
Function: sum_of_lists at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def sum_of_lists(N):
     2         1       1000.0   1000.0      0.0      total = 0
     3         6       4000.0    666.7      0.0      for i in range(5):
     4     25005   10854000.0    434.1     98.3          L = [j ^ (j >> i) for j in range(N)]
     5         5     179000.0  35800.0      1.6          total += sum(L)
     6         1       1000.0   1000.0      0.0      return total

In [9]:
pip install memory_profiler

Note: you may need to restart the kernel to use updated packages.


In [11]:
%load_ext memory_profiler

In [13]:
%memit sum_of_lists(1000000)

peak memory: 239.53 MiB, increment: 75.31 MiB


In [18]:
%%file mprun.ipynb 
def sum_of_lists(N):
    total = 0
    for i in range(5):
        L = [j ^ (j >> i) for j in range(N)]
        total += sum(L)
        del L
    return total 

Overwriting mprun.ipynb


In [21]:
from mprun_demo import sum_of_lists
%mprun -f sum_of_lists sum_of_lists(1000000)

ModuleNotFoundError: No module named 'mprun_demo'

In [23]:
pip install memory_profiler
%load_ext memory_profiler
%mprun -f sum_of_lists sum_of_lists(1000000)

SyntaxError: invalid syntax (3524706412.py, line 1)

In [25]:
pip install memory_profiler

Note: you may need to restart the kernel to use updated packages.


In [27]:
%load_ext memory_profiler
%mprun -f sum_of_lists sum_of_lists(1000000)

The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler
ERROR: Could not find file /var/folders/j4/qzhh77r553z1scwnh3mxkx200000gn/T/ipykernel_1596/1773548912.py



In [29]:
from mprun_demo import sum_of_lists
%mprun -f sum_of_lists sum_of_lists(1000000)

ModuleNotFoundError: No module named 'mprun_demo'

In [1]:
import numpy as np

In [3]:
np?

Type:        module
String form: <module 'numpy' from '/opt/anaconda3/lib/python3.12/site-packages/numpy/__init__.py'>
File:        /opt/anaconda3/lib/python3.12/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = 

In [5]:
# This is the documentaton : --> np? for documentation, np.<TAB> for displaying 
# all contents 

In [7]:
L = list(range(100))

In [9]:
L

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [11]:
type(L[0])

int

In [13]:
# or similarly a list of strings 
L2 = [str(c) for c in L]
L2

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99']

In [15]:
type(L2[0])

str

In [17]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [19]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
import numpy as np 
np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [23]:
# if we want to explicilty set the data type of resulting array, we can use the dtype keyword
np.array([1,2,3,4,5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [25]:
# Nested lists result in multimensional arrays
np.array([range(i, i + 3) for i in [2,3,6]])


array([[2, 3, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
# Create a 3*5 floating-point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
# Create a 3*5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [35]:
# Create an array filled with a linear sequence 
# staring at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
# Create a 3*3 array of uniformly distributed 
# pseudorandom values between 0 and 1
np.random.random((3,3))

array([[0.48511178, 0.03861091, 0.57249033],
       [0.33927164, 0.4773967 , 0.37606351],
       [0.01544222, 0.69649815, 0.11804255]])

In [41]:
#  Create a 3*3 array of uniformly distributed 
# pseudorandom values with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.16015499,  1.3093985 , -1.71450248],
       [-0.69514106, -0.26827589,  0.7421276 ],
       [-0.55098135,  1.20633779, -0.42827769]])

In [45]:
# create a 3*3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[5, 2, 3],
       [6, 6, 7],
       [0, 2, 6]])

In [47]:
# Create a 3*3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
# create an uninitialized array of three integers; the values will be whatever happens
# to already exist at that memory location 
np.empty(3)

array([1., 1., 1.])

In [63]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [65]:
# or using the associated NumPy object:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [67]:
# see the same result


In [71]:
import numpy as np 

rng = np.random.default_rng(seed=1701) # seed for reproducibility

x1 = rng.integers(10, size=6) # one-dimensional array
x2 = rng.integers(10, size=(3,4)) # two-dimensional array
x3 = rng.integers(10, size=(3,4,5)) # three-dimensional array

In [73]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)  # 3 layers, 4 rows and each row has 5 columns 3*4*5=60
print("dtype:   ", x3.dtype)



x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:    int64


In [75]:
x1

array([9, 4, 0, 3, 8, 6])

In [77]:
x1[0]

9

In [79]:
x1[4]

8

In [81]:
x1[-1]

6

In [83]:
# index from the end of the arrays, you can use negative indices 
x1[-2]  # array([9, 4, 0, 3, 8, 6])

8

In [85]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [89]:
x2[0,0]  # [0,0] means first row and first column 

3

In [91]:
x2[2,-1]  # -1 means at the end of the arrays, 2 means the third rows because it counts 0,1,2

9

In [93]:
x2[0,0] = 12 # means first row and first column is equal to 12, so when you
# run the code it displays [12...]

In [95]:
x1[0] = 3.14  # here is truncated to 3 
x1

array([3, 4, 0, 3, 8, 6])

In [97]:
x1

array([3, 4, 0, 3, 8, 6])

x1[:3] # the first 3 elements


In [105]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [107]:
x1[1:4] # middle subarray 4 includes but 4th element 8 not include

array([4, 0, 3])

In [109]:
x1[::2]  # every second element 

array([3, 0, 8])

In [111]:
x1[1::2]  # every second element, starting at index 1

array([4, 3, 6])

In [113]:
x1[::-1]  # all elements reversed 

array([6, 8, 3, 0, 4, 3])

In [115]:
x1[4::-2]

array([8, 0, 3])

In [117]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [121]:
x2[:2, :3]  # first two rows and first three columns 

array([[12,  1,  3],
       [ 4,  0,  2]])

In [123]:
x2[:3, ::2]  # three rows every second columns 

array([[12,  3],
       [ 4,  2],
       [ 0,  6]])

In [125]:
x2[::-1, ::-1] # all rows and columns reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [127]:
x2[:, 0]   # first column of x2, here is only 1st column order

array([12,  4,  0])

In [129]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]


In [131]:
x2_sub[0,0] = 90
print(x2_sub)

[[90  1]
 [ 4  0]]


In [133]:
print(x2)

[[90  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [137]:
x2_sub_copy = x2[:2, :2].copy()  # copy() explicitly copy the data within an array or a subarray
print(x2_sub_copy)

[[90  1]
 [ 4  0]]


In [139]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [141]:
print(x2)

[[90  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [143]:
x = np.arange(1, 10).reshape(3,3)

In [145]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
x = np.array([1,2,3])
x.reshape((1,3)) # row vector via reshape

array([[1, 2, 3]])

In [149]:
grid = np.array([[1, 2, 3],
                [4, 5, 6], 
                [7, 8, 9]])


In [153]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])